POST http://localhost:3003/html
Content-Type: application/json

{
    "url":"https://legal-detail.surge.sh/"
}

###
GET http://localhost:3003/response?url=https://legal-detail.surge.sh/
Content-Type: application/json

# URL DEPLOY 
#https://ufmt-caroline-martins.onrender.com/response